stages:
  acquire_coco:
    cmd: python scripts/acquire_coco.py --out data/raw/coco
    deps:
      - scripts/acquire_coco.py
    outs:
      - data/raw/coco

  generate_synthetic_coco:
    cmd: python scripts/generate_synthetic_dataset_coco.py --out_dir data/raw/generated_coco --num ${dataset.num} --seed ${dataset.seed}
    deps:
      - scripts/generate_synthetic_dataset_coco.py
      - params.yaml
    outs:
      - data/raw/generated_coco

