# scripts/prepare_data.py
import os

# Create the raw data directory
os.makedirs("data/raw", exist_ok=True)

# Example: write a placeholder file
with open("data/raw/sample.txt", "w") as f:
    f.write("This is raw data generated by prepare stage.")
